import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'edittext'
})
export class EdittextPipe implements PipeTransform {
//We change below method signature auto generated by cli to pass arguemet
  //transform(value: unknown, ...args: unknown[]): unknown {
    transform(value: string, length: number): unknown {
    return value.substring(0,length);
  }

}
